---
title: "Data Science Basics for Scientists in Parks"
---

Overview

This workshop is built from the Carpentries lessons. The Carpentries' aim is to teach researchers basic concepts, skills, and tools for working with data so that they can get more done in less time, and with less pain. This workshop uses a tabular ecology dataset and teaches data cleaning, management, analysis and visualization. There are no pre-requisites, and the materials assume no prior knowledge about the tools.

The workshop uses a single tabular data set that contains observations about adorable small mammals over a long period of time in Arizona.

[Setup and installation instructions](setup.md)

Setup and installation video

Overview of the lessons:

  * Data organization in spreadsheets and data cleaning with OpenRefine
  * Introduction to R
  * Data analysis and visualization in R

## Detailed structure

### Session 1: Data organization & cleaning

There are two lessons in this section. The first is a spreadsheet lesson that teaches good data organization, and some data cleaning and quality control checking in a spreadsheet program.

  * [spreadsheet lesson](http://datacarpentry.org/spreadsheet-ecology-lesson/)

The second lesson uses a spreadsheet-like program called [OpenRefine](http://openrefine.org/) to teach data cleaning and filtering

  * [OpenRefine lesson](http://datacarpentry.org/OpenRefine-ecology-lesson/) 

### Session 2: Data analysis & visualization

These lessons include a basic introduction to R syntax, importing CSV data, and subsetting and merging data. It finishes with calculating summary statistics and creating simple plots.

  * [R lesson](http://datacarpentry.org/R-ecology-lesson/)
